
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int METOD = 45;
  public static final int NUMERO = 2;
  public static final int INCREMENT = 39;
  public static final int MULT = 11;
  public static final int SO = 29;
  public static final int STRING_CONTENT = 55;
  public static final int CHAR = 7;
  public static final int INTVALUE = 4;
  public static final int CORCCIERRA = 20;
  public static final int CHAR_CONTENT = 56;
  public static final int METODCLOSE = 46;
  public static final int WHILECLOSE = 41;
  public static final int RESTA = 10;
  public static final int REPEAT = 42;
  public static final int SWITCHCLOSE = 35;
  public static final int PARENABRE = 15;
  public static final int PRINTLN = 52;
  public static final int EXECUTE = 50;
  public static final int IFCLOSE = 32;
  public static final int PUNTOCOMA = 18;
  public static final int FOR = 36;
  public static final int FIN = 22;
  public static final int MENORIGUAL = 59;
  public static final int IDENTIFICADOR = 24;
  public static final int ESIGUAL = 61;
  public static final int MAYORQUE = 58;
  public static final int FUN = 47;
  public static final int COMO = 26;
  public static final int UNTIL = 37;
  public static final int SUMA = 9;
  public static final int ASSIGN = 23;
  public static final int UMENOS = 8;
  public static final int IF = 28;
  public static final int UNTIL_CONDITION = 43;
  public static final int MAYORIGUAL = 60;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int DECIMAL = 3;
  public static final int RETURN = 44;
  public static final int TRUE = 53;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int MODULO = 14;
  public static final int PARAMETERS = 49;
  public static final int SWITCH = 33;
  public static final int MENORQUE = 57;
  public static final int CON_VALOR = 27;
  public static final int POTENCIA = 13;
  public static final int DIVD = 12;
  public static final int ELSE = 31;
  public static final int NOESIGUAL = 62;
  public static final int INGRESAR = 25;
  public static final int WHILE = 40;
  public static final int CLOSECASE = 65;
  public static final int OPENCASE = 64;
  public static final int FUNCLOSE = 48;
  public static final int STRING = 5;
  public static final int FORCLOSE = 38;
  public static final int INICIO = 21;
  public static final int FALSE = 54;
  public static final int INVERSE = 63;
  public static final int PARENCIERRA = 16;
  public static final int ELIF = 30;
  public static final int PRINT = 51;
  public static final int DO = 34;
  public static final int CORCABRE = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "DECIMAL",
  "INTVALUE",
  "STRING",
  "BOOLEAN",
  "CHAR",
  "UMENOS",
  "SUMA",
  "RESTA",
  "MULT",
  "DIVD",
  "POTENCIA",
  "MODULO",
  "PARENABRE",
  "PARENCIERRA",
  "COMA",
  "PUNTOCOMA",
  "CORCABRE",
  "CORCCIERRA",
  "INICIO",
  "FIN",
  "ASSIGN",
  "IDENTIFICADOR",
  "INGRESAR",
  "COMO",
  "CON_VALOR",
  "IF",
  "SO",
  "ELIF",
  "ELSE",
  "IFCLOSE",
  "SWITCH",
  "DO",
  "SWITCHCLOSE",
  "FOR",
  "UNTIL",
  "FORCLOSE",
  "INCREMENT",
  "WHILE",
  "WHILECLOSE",
  "REPEAT",
  "UNTIL_CONDITION",
  "RETURN",
  "METOD",
  "METODCLOSE",
  "FUN",
  "FUNCLOSE",
  "PARAMETERS",
  "EXECUTE",
  "PRINT",
  "PRINTLN",
  "TRUE",
  "FALSE",
  "STRING_CONTENT",
  "CHAR_CONTENT",
  "MENORQUE",
  "MAYORQUE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "ESIGUAL",
  "NOESIGUAL",
  "INVERSE",
  "OPENCASE",
  "CLOSECASE"
  };
}

