
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PERCENT = 24;
  public static final int ASTERISK = 17;
  public static final int PUNTOYCOMA = 9;
  public static final int CONCATENACION = 15;
  public static final int DOSPUNTOS = 8;
  public static final int RANGE = 11;
  public static final int CONJUNTO = 4;
  public static final int DECIMAL = 6;
  public static final int LINEJUMP = 21;
  public static final int QUESTIONMARK = 19;
  public static final int ASIGNAR = 10;
  public static final int STRING = 7;
  public static final int COMA = 12;
  public static final int SPCOMILLA = 23;
  public static final int COMILLASIMPLE = 14;
  public static final int EOF = 0;
  public static final int SPCS = 22;
  public static final int COMILLA = 13;
  public static final int DISYUNCION = 16;
  public static final int MASMAS = 18;
  public static final int error = 1;
  public static final int NUMERO = 5;
  public static final int CORCHETEABRE = 2;
  public static final int ASCII = 20;
  public static final int CORCHETECIERRA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "CONJUNTO",
  "NUMERO",
  "DECIMAL",
  "STRING",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "ASIGNAR",
  "RANGE",
  "COMA",
  "COMILLA",
  "COMILLASIMPLE",
  "CONCATENACION",
  "DISYUNCION",
  "ASTERISK",
  "MASMAS",
  "QUESTIONMARK",
  "ASCII",
  "LINEJUMP",
  "SPCS",
  "SPCOMILLA",
  "PERCENT"
  };
}

